#include "tact.h"


//Setings FEI
void fll_init (void)
{
	MCG->C1 &= ~ MCG_C1_CLKS_MASK;
	while (MCG->S & MCG_S_CLKST_MASK);
	MCG->C1 |= MCG_C1_IREFS_MASK;
	while (!(MCG->S & MCG_S_IREFST_MASK));
	
	MCG->C2 &= ~(3 << MCG_C2_RANGE_SHIFT);
	SIM->CLKDIV1 &= ~(0x0F << SIM_CLKDIV1_OUTDIV1_SHIFT|0x0F << SIM_CLKDIV1_OUTDIV2_SHIFT|0x0F << SIM_CLKDIV1_OUTDIV4_SHIFT);
	SIM->CLKDIV1 |= SIM_CLKDIV1_OUTDIV1(0) | SIM_CLKDIV1_OUTDIV2(1) | SIM_CLKDIV1_OUTDIV4(3);
	MCG->C4 |= MCG_C4_DRST_DRS(3);
	while (((MCG->C4 & MCG_C4_DRST_DRS_MASK) >> MCG_C4_DRST_DRS_SHIFT) != 3) ;
}

void FEI_init (void)
{
	SMC->PMPROT = (SMC_PMPROT_AHSRUN_MASK | SMC_PMPROT_AVLP_MASK);
	SIM_CLKDIV1 = SIM_CLKDIV1_OUTDIV1(0x00) |
                SIM_CLKDIV1_OUTDIV2(0x00) |
                SIM_CLKDIV1_OUTDIV4(0x01);
	SIM->SOPT2 &= ~SIM_SOPT2_PLLFLLSEL_MASK  ;
	MCG->C2 &= ~MCG_C2_EREFS_MASK;
	MCG->C1 |= MCG_C1_IREFS_MASK;
	
}

void FEE_init (void)
{
}


